"""empty message

Revision ID: 98cadd8f51d5
Revises: 
Create Date: 2023-01-24 15:45:01.349319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cadd8f51d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=True),
    sa.Column('is_publish', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('topping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_special', sa.Boolean(), nullable=True),
    sa.Column('is_vegan', sa.Boolean(), nullable=True),
    sa.Column('is_publish', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['food_category.category_id'], ),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('topping_food',
    sa.Column('topping', sa.Integer(), nullable=False),
    sa.Column('food', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food'], ['food.food_id'], ),
    sa.ForeignKeyConstraint(['topping'], ['topping.id'], ),
    sa.PrimaryKeyConstraint('topping', 'food')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topping_food')
    op.drop_table('food')
    op.drop_table('topping')
    op.drop_table('food_category')
    # ### end Alembic commands ###
